update Android target to 17

diff --git a/tools/build-release b/tools/build-release
--- a/tools/build-release
+++ b/tools/build-release
@@ -5,10 +5,10 @@
 # of Android Terminal Emulator.
 set -e
 
-if [ ! -f "$HOME/Documents/workspace/keystore/jackpal.keystore" ]; then
-    echo "Release keystore file is missing. Cannot build release build."
-    exit 1
-fi
+#if [ ! -f "$HOME/Documents/workspace/keystore/jackpal.keystore" ]; then
+#    echo "Release keystore file is missing. Cannot build release build."
+#    exit 1
+#fi
 
 if [ -z "${ANDROID_NDK_ROOT+xxx}" ]; then
 	echo "Please define ANDROID_NDK_ROOT to point to the Android NDK"
